# Generated by Django 4.2.1 on 2023-05-22 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='auther',
            new_name='author',
        ),
    ]
