# Generated by Django 4.2.1 on 2023-05-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Karzinka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('information', models.TextField()),
                ('created_date', models.TimeField(auto_now=True)),
            ],
        ),
    ]
