# Generated by Django 4.2.1 on 2023-05-21 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karzinka', '0002_category_karzinka_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karzinka',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='karzinka', to='karzinka.category'),
        ),
    ]
