# Generated by Django 4.2.1 on 2023-05-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karzinka', '0003_alter_karzinka_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='karzinka',
            name='tags',
            field=models.ManyToManyField(to='karzinka.tags'),
        ),
    ]
