# Generated by Django 4.2.1 on 2023-05-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karzinka', '0004_tags_karzinka_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='karzinka',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
